export enum actionType {
  ADD_QUESTION = "ADD_QUESTION",
  ADD_OPTION = "ADD_OPTION",
  CLEAR_QUIZ = "CLEAR_QUIZ",
  REMOVE_OPTION = "REMOVE_OPTION",
  REMOVE_QUESTION = "REMOVE_QUESTION",
  SWITCH_CORRECT_OPTION = "SWITCH_CORRECT_OPTION",
}